README.md
This repository must be maintaned in English.
Replaces *Installer do OpenCart* per *OpenCart Installer*
=> Edit title that was written with a portuguese term

catalog/model/extension/payment/mundipagg_order_processing.php, system/library/mundipagg/src/Controller/WebHook.php, system/library/mundipagg/src/Enum/OrderstatusEnum.php
Move OrderStatusEnum to Enum directory
=> Improve code organization

admin/controller/extension/payment/mundipagg.php, system/library/mundipagg/src/Controller/CreditCardSettings.php
Improve module settings organization
Things were a little messy, now is a little more organized
CreditCardSettings was created to handle all the credit card module settings
=> Add credit card settings

.travis.yml, composer.json, features/bootstrap/FeatureContext.php, features/install.feature
**What?** Add behat to travis and fix tests
**How?** Upgrade `.travis.yml` and fix the `install.feature`
=> run behat tests in Travis-CI

admin/controller/extension/payment/mundipagg.php, admin/language/en-gb/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig, system/library/mundipagg/src/Order.php
Create mapping to custom fields  Number and Complement
Correctly relation between opencart and mundipagg fields.
=> ➕Add number and complement to address

admin/language/en-gb/extension/payment/mundipagg.php, admin/model/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig, catalog/language/en-gb/extension/payment/mundipagg.php, catalog/model/extension/payment/mundipagg_credit_card.php, catalog/view/theme/default/template/extension/payment/mundipagg.twig, system/library/mundipagg/src/Order.php
Add incremental interest
Increase interest installment by installment.
Improving installments creator method.
=> Add incremental interest

admin/controller/extension/payment/mundipagg.php, admin/language/en-gb/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig
Create custom fields combo boxes.
Help user to select custom fields.
Getting  and showing custom fields created by user.
=> Create custom fields combo boxes.

catalog/controller/extension/payment/mundipagg_events.php
Remove unused method
Clean code
=> ➖ Remove unused method

install.xml
=> Add installxml

admin/controller/extension/payment/mundipagg.php, admin/model/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig, behat.yml, catalog/view/theme/default/template/extension/payment/mundipagg.twig, modman
Change some of admin input types
=> Change some of admin input types

admin/model/extension/payment/mundipagg.php, modman, system/library/mundipagg/src/LogMessages.php, system/library/mundipagg/src/Order.php
Save mundipagg charge into database.
Using events
=> ➕ create charge

admin/model/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg_webhook.php, modman, system/library/mundipagg/src/Controller/Settings.php, system/library/mundipagg/src/Controller/WebHook.php, system/library/mundipagg/src/ErrorEnum.php
=> Fix package issues.

.env.example
Added documentation to .env.example
To help on new installs.
=> Added documentation to .env.example

admin/model/extension/payment/mundipagg.php, install.xml, system/library/mundipagg/src/Controller/Settings.php, system/library/mundipagg/src/ErrorEnum.php, system/library/mundipagg/src/LogMessages.php
Fix module installation sql script.
Module installation was not working.
Remove wrong database call.
=> Fix installation sql script

tests/catalog/MundipaggTest.php
prevent user creating before all test steps
=> Fix test: prevent user creating before all test steps

admin/controller/extension/payment/mundipagg_events.php
fix mundipagg logo url
The admin root is needed on image url prefix.
Add url prefix.
=> 🐛 fix mundipagg logo url

admin/view/template/extension/payment/mundipagg.twig
Fix custom fields selection
Custom fields selection is broken.
Refact selection logic
=> Fix custom fields selection

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/template/extension/payment/mundipagg.twig
Fix url payment boleto
The payment success fail on url redirect
fix it
=> Fix url payment boleto

system/library/mundipagg/src/Order.php
Added cents on product price
To send to api the correct price
By formatting the price correctly.
=> 🐛 Fixed product price

README.md, RoboFile.php, install.xml, system/library/mundipagg/src/Controller/Settings.php, system/library/mundipagg/src/ErrorEnum.php, system/library/mundipagg/src/LogMessages.php
Implement command to create package
I'm a lazy man and I do not want to run this manually every time
Using PHP
=> Implement command to create package

admin/controller/extension/payment/mundipagg_events.php
Few error messages were being shown in Sales/Order
Initialize $cancel and $cancelCapture
=> Fix Sales/Order admin panel error

catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/template/extension/payment/mundipagg.twig
Implement checkout form validation
=> Implement form validation

catalog/view/theme/default/template/extension/payment/mundipagg.twig, composer.lock
Add bootstrap danger class to credit card form errors
Improve user experience.
=> Add css class to form errors.

admin/model/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg_events.php, install.xml, system/library/mundipagg/src/Controller/Settings.php, system/library/mundipagg/src/Customer.php, system/library/mundipagg/src/LogMessages.php, system/library/mundipagg/src/Order.php
Create saved credit card table.
Allow to get credit card saved data to use in one click orders.
Add new methods in module installation script.
=> Create saved credit cards table

catalog/model/extension/payment/mundipagg_customer.php, system/library/mundipagg/src/Order.php
Save MundiPagg customer in Opencart table.
Why not?
Save customer id if not exists.
=> Save MundiPagg customer in Opencart table

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/template/extension/payment/mundipagg.twig, catalog/view/theme/default/template/extension/payment/mundipagg_boleto.twig, catalog/view/theme/default/template/extension/payment/mundipagg_credit_card.twig, catalog/view/theme/default/template/extension/payment/mundipagg_creditcard.twig, modman
Split credit card and boleto template.
Improve code structure and code maintainability.
Split template in 3 files.
=> Split credit card and boleto template

catalog/controller/extension/payment/mundipagg.php, catalog/language/en-gb/extension/payment/mundipagg.php, catalog/language/pt-br/extension/payment/mundipagg.php, catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/stylesheet/mundipagg/mundipagg.css, catalog/view/theme/default/template/extension/payment/mundipagg_creditcard.twig, catalog/view/theme/default/template/extension/payment/mundipagg_new_creditcard.twig, catalog/view/theme/default/template/extension/payment/mundipagg_saved_creditcard.twig
Show and switch new/saved credit card.
Allow switch between new and saved.
Show/hide by js.
=> Show and switch new/saved credit card.

admin/controller/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig
Show boleto due at value in admin panel.
Boleto tab is not showing this information.
Fix variable name.
=> Show boleto due at value in admin panel

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/stylesheet/mundipagg/mundipagg.css, catalog/view/theme/default/template/extension/payment/mundipagg.twig, catalog/view/theme/default/template/extension/payment/mundipagg_boleto.twig, install.xml, system/library/mundipagg/src/Controller/Settings.php, system/library/mundipagg/src/LogMessages.php, system/library/mundipagg/src/Order.php
Deal with client issues.
Problems during boleto generate.
Call boleto generate method by ajax before page redirect.
=> Intercollor

admin/model/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg_events.php, catalog/view/theme/default/template/extension/payment/mundipagg_saved_credit_card_account_content.twig
Add Saved cards account menu item
To let customer reach My Cards Page from account page side Menu.
=> Add Saved cards account menu item

admin/controller/extension/payment/mundipagg.php
Fix incorrect captured value
To capture correct value in panel.
=> Fix incorrect captured value

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/stylesheet/mundipagg/mundipagg.css, catalog/view/theme/default/template/extension/payment/mundipagg/boleto_credit_card.twig, catalog/view/theme/default/template/extension/payment/mundipagg/mundipagg.twig
| What?         | Create boleto + credit card interface.
| Why?          | Prepare this new payment method.
| How?          | Create new templates.
IN DEVELOPMENT
=> Boleto  + credit card interface

admin/model/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg_events.php, catalog/controller/extension/payment/mundipagg_saved_creditcards.php, catalog/language/en-gb/extension/payment/mundipagg.php, catalog/language/pt-br/extension/payment/mundipagg.php, catalog/model/extension/payment/mundipagg_boleto_link.php, catalog/view/theme/default/template/extension/payment/mundipagg/success/order_info.twig, system/library/mundipagg/src/LogMessages.php
| What?         | Show boleto link on checkout success
| Why?          | Customers must have a boleto link on checkout.
| How?          | Creating events and saving boleto link on database.
READY
=> Show boleto link on checkout success

admin/controller/extension/payment/mundipagg.php, admin/language/en-gb/extension/payment/mundipagg.php, admin/language/pt-br/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig, catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/template/extension/payment/mundipagg/mundipagg.twig, system/library/mundipagg/src/Settings/BoletoCreditCard.php, system/library/mundipagg/src/Settings/Boletocc.php
| What?         | Enable/disable Boleto  + Creditcard payment method.
| Why?          | To show or hide  Boleto  + Creditcard payment method on checkout.
| How?          | Adding a form into module's configurations. 
READY
=>  Enable/disable Boleto  + Creditcard payment method.

catalog/controller/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg_events.php, catalog/view/theme/default/stylesheet/mundipagg/mundipagg.css, catalog/view/theme/default/template/extension/payment/mundipagg/boleto/base.twig, catalog/view/theme/default/template/extension/payment/mundipagg/boleto/info.twig, catalog/view/theme/default/template/extension/payment/mundipagg/boleto/submit.twig, catalog/view/theme/default/template/extension/payment/mundipagg/boleto_credit_card.twig, catalog/view/theme/default/template/extension/payment/mundipagg/mundipagg.twig, catalog/view/theme/default/template/extension/payment/mundipagg/success/order_info.twig, system/library/mundipagg/src/Order.php
| What?         | Add Boleto + Creditcard payment method
| Why?          | To allow customers to use  Boleto  + Creditcard payment method on checkout.
| How?          | Combining primitive payment views and preparing the backend to the new method.
READY
=> Add Boleto + Creditcard payment method

catalog/controller/extension/payment/mundipagg.php, system/library/mundipagg/src/Order.php
| What?         | Fixed credit card invalid payment method
| Why?          | To module work properly.
READY
=> Fixed invalid payment method

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/template/extension/payment/mundipagg/boleto_credit_card.twig, catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
| What?         | Fixed sensitive card info are sent to backend and other minor bugs.
| Why?          | For security reasons, card info must not be sent to backend.
| How?          | Set a script to remove sensitive card info before the form submit.
READY
=> Fixed sensitive card info are sent to backend and other minor bugs.

system/library/mundipagg/src/Model/Installments.php
| What?         | Round interest value on installments
| Why?          | For presentation of values with 2 decimal digits.
| How?          | Round the result of value calculation.
READY
=> Round interest value on installments

system/library/mundipagg/src/Model/Installments.php
| What?         | Round installment tax value and fix first installment with interest skip.
| Why?          | For presentation of values with 2 decimal digits and fix skip.
| How?          | Round the result of installment tax value calculation and correct a for loop initialization.
READY
=> Round installment tax value and fix first installment with interest skip

catalog/controller/extension/payment/mundipagg.php
| What?         | Fix installments count on new card.
| Why?          | To send correct installments to API.
READY
=> Fix installments count on new card

.github/PULL_REQUEST_TEMPLATE.md, catalog/model/extension/payment/mundipagg_boleto_link.php, catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
| What?         | Fix Not focusable form control 
|                     | Add pull request template
| Why?          | When checkout an order with decimal value on the price, the browser stop the validation processes.
|                    | To ease the process of create a new Pull Request.
| How?          | Add step attribute to number type input on form
|                    | Add a template file.
READY
=> Fix Not focusable form control / add pull request template

admin/controller/extension/payment/mundipagg_events.php, admin/view/template/extension/payment/mundipagg/order_actions.twig, system/library/mundipagg/composer.lock
| What?         | Fix mundipagg M button.
| Why?          | Fix it.
| How?          | Refact bad code and redirect to order preview.
Before
After
=> #112 Fix mundipagg M button

system/library/mundipagg/src/Controller/Settings.php, system/library/mundipagg/src/Order.php, system/library/mundipagg/src/Settings/AntiFraud.php, system/library/mundipagg/src/Settings/General.php
**Closes https://github.com/mundipagg/plug-team/issues/114**
| What?         | Move anti fraud settings to its own controller
| Why?          | Split responsibilities.
=> #114 Move anti fraud settings to its own controller

catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/credit_card.twig
| Issues      |  mundipagg/plug-team#167
| What?         | Fix installments update on creditcard number input.
| Why?          | On checkout, installments weren't updating correctly on card number input.
| How?          | Fixed javascript.
READY
=> Fix installments update on creditcard number input.

admin/model/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg.php, catalog/controller/extension/payment/mundipagg_events.php, catalog/language/en-gb/extension/payment/mundipagg.php, catalog/language/pt-br/extension/payment/mundipagg.php, catalog/model/extension/payment/mundipagg_boleto_link.php, catalog/model/extension/payment/mundipagg_order_boleto_info.php, catalog/model/extension/payment/mundipagg_order_creditcard_info.php, catalog/view/theme/default/template/extension/payment/mundipagg/account/order_info.twig, system/library/mundipagg/src/Controller/TwoCreditCards.php, system/library/mundipagg/src/Model/Order.php
| Issues      | mundipagg/plug-team#163
| What?         | Show order info on my account order review
| Why?          | To improve usability.
| How?          | Add a new section to order review page of My Account.
READY
=> Show order info on my account order review

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/template/extension/payment/mundipagg/multi_buyer_form.twig
| What?         | Fix validations require on multi buyer feature
| Why?          | The validation of some multi-buyer's fields was been required even if the multi buyer wasn't selected
| How?          | We verify before validate if the multi buyer was selected
READY / IN DEVELOPMENT
=> Fix validations require on multi buyer feature

admin/controller/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg_confirmUpdateCharge.twig, admin/view/template/extension/payment/mundipagg_previewChangeCharge.twig
| Issues        | https://github.com/mundipagg/plug-team/issues/232
| What?         | Improve charges details screen
| Why?          | To improve the usability
| How?          | Improve forms and buttons of capture and cancel charges
**Charge Grid:**
- Before:
- After:
**Charge Form:**
- Before:
- After:
=> Improve charges details screen

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/template/extension/payment/mundipagg/multi_buyer_form.twig, system/library/mundipagg/src/Controller/TwoCreditCards.php, system/library/mundipagg/src/MultiBuyer.php
| Issues         | https://github.com/mundipagg/plug-team/issues/241 / https://github.com/mundipagg/plug-team/issues/236
| What?         | Some variables were undefined and breaking the code.
| Why?          | undefineds variables
| How?          | to verify if the variables are setted
READY / IN DEVELOPMENT
=> Fix undefined variables on cards saved

tests/catalog/MundipaggTest.php
| Issues         | https://github.com/mundipagg/plug-team/issues/277
| What?         | Change API url
| Why?          | To communicate with the correct api 
| How?          | Changing url of api
=> Change API url

catalog/controller/extension/payment/mundipagg.php, catalog/model/extension/payment/mundipagg_credit_card.php, catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js, catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
| Issues         | https://github.com/mundipagg/plug-team/issues/238
| What?         | To fix bug of NaN on autobalance amount
| Why?          | When the amount value is clean, the string "NaN' appear on input and we can't change the value 
| How?          | Verify if the value is empty to set the minimum value of division on 2 payments methods
=> Fix NaN on autobalance amount

catalog/controller/extension/payment/mundipagg.php, catalog/view/theme/default/template/extension/payment/mundipagg/boleto/base.twig, catalog/view/theme/default/template/extension/payment/mundipagg/boleto/submit.twig, catalog/view/theme/default/template/extension/payment/mundipagg/mundipagg.twig, catalog/view/theme/default/template/extension/payment/mundipagg/success/order_info.twig, system/library/mundipagg/src/Order.php
| Issues         | https://github.com/mundipagg/plug-team/issues/237
| What?         | Implement Mulyibuyer to Boleto and Boleto + Credit Card
| Why?          | To allow the customer create boleto to other buyer
| How?          |  When fill the form of multi buyer on boleto method, the informations will inputted on boleto's data
=> Implement multibuyer to boleto

admin/view/template/extension/payment/mundipagg/recurrence/templates/base.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/create.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/form_plan.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/form_single.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/panelPlanFrequency.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/panelSingleFrequency.twig, docs/diagrams.mdj, system/library/mundipagg/src/Aggregates/Template/TemplateEntity.php, system/library/mundipagg/src/Aggregates/Template/TemplateRoot.php, system/library/mundipagg/src/Controller/Recurrence/Templates.php, system/library/mundipagg/src/Repositories/AbstractRep.php, system/library/mundipagg/src/Repositories/TemplateRepository.php
| Issues | mundipagg/plug-team#306
| What?         |  Merged Plans and Subscriptions Template CRUD - UPDATE
| Why?          | To edit saved plan/single templates.
| How?          | Changes on endpoints, repository and twig templates.
=> Plans and Subscriptions Template CRUD - UPDATE

admin/view/template/extension/payment/mundipagg/recurrence/plans/productFormTabContent.twig, docs/diagrams.mdj, system/library/mundipagg/src/Controller/Events.php, system/library/mundipagg/src/Controller/Recurrence/Templates.php, system/library/mundipagg/src/Repositories/AbstractRep.php, system/library/mundipagg/src/Repositories/Bridges/AbstractDatabaseBridge.php, system/library/mundipagg/src/Repositories/Bridges/OpencartDatabaseBridge.php, system/library/mundipagg/src/Repositories/TemplateRepository.php
| Issues | mundipagg/plug-team#306
| What?         | Add an abstraction layer to database operations
| Why?          | To decouple plan templates CRUD backend from Opencart
| How?          | Create an Abstract/Interface class and concrete class to implement database operations.
=> Add an abstraction layer to database operations

catalog/controller/extension/payment/mundipagg.php
| What?         | Fix guest orders
| Why?          | Allow to create orders for guest customers.
| How?          | Remove "isLogged" verification
=> Fix guest orders

admin/controller/extension/payment/mundipagg.php, admin/model/extension/payment/mundipagg.php, system/library/mundipagg/src/Aggregates/RecurrencyProduct/RecurrencyProductRoot.php, system/library/mundipagg/src/Controller/Events.php, system/library/mundipagg/src/Controller/Recurrence/Plans.php, system/library/mundipagg/src/Factories/RecurrencyProductRootFactory.php, system/library/mundipagg/src/Repositories/RecurrencyProductRepository.php
| What?         | Plans CRUD - D
| Why?          | To delete plan products
| How?          | By intercepting Opencart default product delete process.
=> Plans CRUD - D

admin/view/template/extension/payment/mundipagg/recurrence/templates/create.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig, admin/view/template/extension/payment/mundipagg/recurrence/templates/form_single.twig, system/library/mundipagg/src/Aggregates/Template/TemplateEntity.php
| What?         | The form was being submit empty
| Why?          | Because the button was being used by 2 forms
| How?          | Submit only the form that is active on page
=> Fix empty form submit

admin/language/en-gb/extension/payment/mundipagg.php, admin/language/pt-br/extension/payment/mundipagg.php, admin/view/template/extension/payment/mundipagg.twig, catalog/view/theme/default/template/extension/payment/mundipagg/boleto/info.twig, system/library/mundipagg/src/Settings/Boleto.php
| What?         | Custom boleto checkout message.
| Why?          | To enable the cofnig of custom boleto checkout message.
| How?          | Translation intercept.
=> Custom boleto checkout message.
